image:
  file: ./.devcontainer/Dockerfile
  context: ./.devcontainer
# Commands to start on workspace startup
tasks:
  - init: npm install&npm install -g @aws-amplify/cli
    command: npm run dev
# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview